application: mountainmetrics
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /tasks/process/.*
  script: cronprocesstasks.py
  login: admin

- url: .*
  script: main.py
